require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TheDaysController do

  def mock_the_day(stubs={})
    @mock_the_day ||= mock_model(TheDay, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all the_days as @the_days" do
      TheDay.stub(:all) { [mock_the_day] }
      get :index
      assigns(:the_days).should eq([mock_the_day])
    end
  end

  describe "GET show" do
    it "assigns the requested the_day as @the_day" do
      TheDay.stub(:find).with("37") { mock_the_day }
      get :show, :id => "37"
      assigns(:the_day).should be(mock_the_day)
    end
  end

  describe "GET new" do
    it "assigns a new the_day as @the_day" do
      TheDay.stub(:new) { mock_the_day }
      get :new
      assigns(:the_day).should be(mock_the_day)
    end
  end

  describe "GET edit" do
    it "assigns the requested the_day as @the_day" do
      TheDay.stub(:find).with("37") { mock_the_day }
      get :edit, :id => "37"
      assigns(:the_day).should be(mock_the_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created the_day as @the_day" do
        TheDay.stub(:new).with({'these' => 'params'}) { mock_the_day(:save => true) }
        post :create, :the_day => {'these' => 'params'}
        assigns(:the_day).should be(mock_the_day)
      end

      it "redirects to the created the_day" do
        TheDay.stub(:new) { mock_the_day(:save => true) }
        post :create, :the_day => {}
        response.should redirect_to(the_day_url(mock_the_day))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved the_day as @the_day" do
        TheDay.stub(:new).with({'these' => 'params'}) { mock_the_day(:save => false) }
        post :create, :the_day => {'these' => 'params'}
        assigns(:the_day).should be(mock_the_day)
      end

      it "re-renders the 'new' template" do
        TheDay.stub(:new) { mock_the_day(:save => false) }
        post :create, :the_day => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested the_day" do
        TheDay.stub(:find).with("37") { mock_the_day }
        mock_the_day.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :the_day => {'these' => 'params'}
      end

      it "assigns the requested the_day as @the_day" do
        TheDay.stub(:find) { mock_the_day(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:the_day).should be(mock_the_day)
      end

      it "redirects to the the_day" do
        TheDay.stub(:find) { mock_the_day(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(the_day_url(mock_the_day))
      end
    end

    describe "with invalid params" do
      it "assigns the the_day as @the_day" do
        TheDay.stub(:find) { mock_the_day(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:the_day).should be(mock_the_day)
      end

      it "re-renders the 'edit' template" do
        TheDay.stub(:find) { mock_the_day(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested the_day" do
      TheDay.stub(:find).with("37") { mock_the_day }
      mock_the_day.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the the_days list" do
      TheDay.stub(:find) { mock_the_day }
      delete :destroy, :id => "1"
      response.should redirect_to(the_days_url)
    end
  end

end
